name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t nitishnandan/my-app:latest .
          docker tag nitishnandan/my-app:latest nitishnandan/my-app:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        if: github.event_name == 'push'
        run: |
          docker push nitishnandan/my-app:latest
          docker push nitishnandan/my-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Image Tag in Kubernetes Manifest
        run: |
          sed -i "s|image: nitishnandan/my-app:.*|image: nitishnandan/my-app:${{ github.sha }}|" k8s/deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update deployment.yaml with new image tag: ${{ github.sha }}" || echo "No changes to commit"
          git push origin main

      - name: Deploy to Kubernetes using ArgoCD
        run: |
          argocd app sync my-app