apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    version: blue  # Change to green during deployment switch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
